const kanaPatterns = {
    "あ": ["a"], "い": ["i"], "う": ["u"], "え": ["e"], "お": ["o"],
    "か": ["ka"], "き": ["ki"], "く": ["ku"], "け": ["ke"], "こ": ["ko"],
    "さ": ["sa"], "し": ["shi", "si"], "す": ["su"], "せ": ["se"], "そ": ["so"],
    "た": ["ta"], "ち": ["chi", "ti"], "つ": ["tsu", "tu"], "て": ["te"], "と": ["to"],
    "な": ["na"], "に": ["ni"], "ぬ": ["nu"], "ね": ["ne"], "の": ["no"],
    "は": ["ha"], "ひ": ["hi"], "ふ": ["fu", "hu"], "へ": ["he"], "ほ": ["ho"],
    "ま": ["ma"], "み": ["mi"], "む": ["mu"], "め": ["me"], "も": ["mo"],
    "や": ["ya"], "ゆ": ["yu"], "よ": ["yo"],
    "ら": ["ra"], "り": ["ri"], "る": ["ru"], "れ": ["re"], "ろ": ["ro"],
    "わ": ["wa"], "を": ["wo"], "ん": ["n"],
    "が": ["ga"], "ぎ": ["gi"], "ぐ": ["gu"], "げ": ["ge"], "ご": ["go"],
    "ざ": ["za"], "じ": ["ji", "zi"], "ず": ["zu"], "ぜ": ["ze"], "ぞ": ["zo"],
    "だ": ["da"], "ぢ": ["di"], "づ": ["du"], "で": ["de"], "ど": ["do"],
    "ば": ["ba"], "び": ["bi"], "ぶ": ["bu"], "べ": ["be"], "ぼ": ["bo"],

    // 半濁音
    "ぱ": ["pa"], "ぴ": ["pi"], "ぷ": ["pu"], "ぺ": ["pe"], "ぽ": ["po"],
    "きゃ": ["kilya", "kixya", "kya"], "きゅ": ["kilyu", "kixyu", "kyu"], "きょ": ["kilyo", "kixyo", "kyo"],
    "ぎゃ": ["gilya", "gixya", "gya"], "ぎゅ": ["gilyu", "gixyu", "gyu"], "ぎょ": ["gilyo", "gixyo", "gyo"],
    "しゃ": ["sha", "silya", "sixya", "sya"], "しゅ": ["shu", "silyu", "sixyu", "syu"], "しょ": ["sho", "silyo", "sixyo", "syo"],
    "じゃ": ["ja", "jilya", "jixya", "jya", "zilya", "zixya", "zya"], "じゅ": ["jilyu", "jixyu", "ju", "jyu", "zilyu", "zixyu", "zyu"], "じょ": ["jilyo", "jixyo", "jo", "jyo", "zilyo", "zixyo", "zyo"],
    "ちゃ": ["cha", "tilya", "tixya", "tya"], "ちゅ": ["chu", "tilyu", "tixyu", "tyu"], "ちょ": ["cho", "tilyo", "tixyo", "tyo"],
    "にゃ": ["nya","nilya", "nixya" ], "にゅ": [ "nyu","nilyu", "nixyu"], "にょ": ["nyo","nilyo", "nixyo" ],
    "ひゃ": ["hya","hilya", "hixya" ], "ひゅ": [ "hyu","hilyu", "hixyu"], "ひょ": ["hyo","hilyo", "hixyo" ],
    "びゃ": ["bya","bilya", "bixya" ], "びゅ": [ "byu","bilyu", "bixyu"], "びょ": ["byo","bilyo", "bixyo" ],
    "ぴゃ": ["pya","pilya", "pixya" ], "ぴゅ": [ "pyu","pilyu", "pixyu"], "ぴょ": ["pyo","pilyo", "pixyo" ],
    "みゃ": ["mya","milya", "mixya" ], "みゅ": [ "myu","milyu", "mixyu"], "みょ": ["myo","milyo", "mixyo" ],
    "りゃ": ["rya","rilya", "rixya" ], "りゅ": [ "ryu","rilyu", "rixyu"], "りょ": ["ryo","rilyo", "rixyo" ],

    // 促音（手動追加）
    "っか": ["kka"], "っき": ["kki"], "っく": ["kku"], "っけ": ["kke"], "っこ": ["kko"],
    "っさ": ["ssa"], "っし": ["sshi", "ssi"], "っす": ["ssu"], "っせ": ["sse"], "っそ": ["sso"],
    "った": ["tta"], "っち": ["cchi", "tti"], "っつ": ["ttsu", "ttu"], "って": ["tte"], "っと": ["tto"],
    "っは": ["hha"], "っひ": ["hhi"], "っふ": ["ffu", "hhu"], "っへ": ["hhe"], "っほ": ["hho"],
    "っま": ["mma"], "っみ": ["mmi"], "っむ": ["mmu"], "っめ": ["mme"], "っも": ["mmo"],
    "っら": ["rra"], "っり": ["rri"], "っる": ["rru"], "っれ": ["rre"], "っろ": ["rro"],
    "っきゃ": ["kkilya", "kkixya", "kkya"], "っきゅ": ["kkilyu", "kkixyu", "kkyu"], "っきょ": ["kkilyo", "kkixyo", "kkyo"],
    "っしゃ": ["ssha", "ssilya", "ssixya", "ssya", "sshilya", "sshixya"], "っしゅ": ["sshu", "ssilyu", "ssixyu", "ssyu", "sshilyu", "sshixyu"], "っしょ": ["ssho", "ssilyo", "ssixyo", "ssyo", "sshilyo", "sshixyo"],
    "っちゃ": ["ccha", "ttilya", "ttixya", "ttya"], "っちゅ": ["cchu", "ttilyu", "ttixyu", "ttyu"], "っちょ": ["ccho", "ttilyo", "ttixyo", "ttyo"],

    //ん系
    "ん": ["nn", "xn"],
    "んか": ["nka", "nnka", "xnka"], "んき": ["nki", "nnki", "xnki"], "んく": ["nku", "nnku", "xnku"], "んけ": ["nke", "nnke", "xnke"], "んこ": ["nko", "nnko", "xnko"],
    "んさ": ["nnsa", "nsa", "xnsa"], "んし": ["nnshi", "nnsi", "nshi", "nsi", "xnshi", "xnsi"], "んす": ["nnsu", "nsu", "xnsu"], "んせ": ["nnse", "nse", "xnse"], "んそ": ["nnso", "nso", "xnso"],
    "んた": ["nnta", "nta", "xnta"], "んち": ["nchi", "nnchi", "nnti", "nti", "xnchi", "xnti"], "んつ": ["nntsu", "nntu", "ntsu", "ntu", "xntsu", "xntu"], "んて": ["nnte", "nte", "xnte"], "んと": ["nnto", "nto", "xnto"],
    "んは": ["nha", "nnha", "xnha"], "んひ": ["nhi", "nnhi", "xnhi"], "んふ": ["nfu", "nhu", "nnfu", "nnhu", "xnfu", "xnhu"], "んへ": ["nhe", "nnhe", "xnhe"], "んほ": ["nho", "nnho", "xnho"],
    "んま": ["nma", "nnma", "xnma"], "んみ": ["nmi", "nnmi", "xnmi"], "んむ": ["nmu", "nnmu", "xnmu"], "んめ": ["nme", "nnme", "xnme"], "んも": ["nmo", "nnmo", "xnmo"],
    "んや": ["nnya", "nya", "xnya"], "んゆ": ["nnyu", "nyu", "xnyu"], "んよ": ["nnyo", "nyo", "xnyo"],
    "んら": ["nnra", "nra", "xnra"], "んり": ["nnri", "nri", "xnri"], "んる": ["nnru", "nru", "xnru"], "んれ": ["nnre", "nre", "xnre"], "んろ": ["nnro", "nro", "xnro"],
    "んわ": ["nnwa", "nwa", "xnwa"], "んを": ["nnwo", "nwo", "xnwo"],
    "んが": ["nga", "nnga", "xnga"], "んぎ": ["ngi", "nngi", "xngi"], "んぐ": ["ngu", "nngu", "xngu"], "んげ": ["nge", "nnge", "xnge"], "んご": ["ngo", "nngo", "xngo"],
    "んざ": ["nnza", "nza", "xnza"], "んじ": ["nji", "nnji", "nnzi", "nzi", "xnji", "xnzi"], "んず": ["nnzu", "nzu", "xnzu"], "んぜ": ["nnze", "nze", "xnze"], "んぞ": ["nnzo", "nzo", "xnzo"],
    "んだ": ["nda", "nnda", "xnda"], "んぢ": ["ndi", "nndi", "xndi"], "んづ": ["ndu", "nndu", "xndu"], "んで": ["nde", "nnde", "xnde"], "んど": ["ndo", "nndo", "xndo"],
    "んば": ["nba", "nnba", "xnba"], "んび": ["nbi", "nnbi", "xnbi"], "んぶ": ["nbu", "nnbu", "xnbu"], "んべ": ["nbe", "nnbe", "xnbe"], "んぼ": ["nbo", "nnbo", "xnbo"],
    "んぱ": ["nnpa", "npa", "xnpa"], "んぴ": ["nnpi", "npi", "xnpi"], "んぷ": ["nnpu", "npu", "xnpu"], "んぺ": ["nnpe", "npe", "xnpe"], "んぽ": ["nnpo", "npo", "xnpo"],
    "んきゃ": ["nkya", "nkilya", "nkixya", "nnkilya", "nnkixya", "nnkya", "xnkilya", "xnkixya", "xnkya"], "んきゅ": ["nkyu", "nkilyu", "nkixyu", "nnkilyu", "nnkixyu", "nnkyu", "xnkilyu", "xnkixyu", "xnkyu"], "んきょ": ["nkyo", "nkilyo", "nkixyo", "nnkilyo", "nnkixyo", "nnkyo", "xnkilyo", "xnkixyo", "xnkyo"],
    "んぎゃ": ["ngya", "ngilya", "ngixya", "nngilya", "nngixya", "nngya", "xngilya", "xngixya", "xngya"], "んぎゅ": ["ngyu", "ngilyu", "ngixyu", "nngilyu", "nngixyu", "nngyu", "xngilyu", "xngixyu", "xngyu"], "んぎょ": ["ngyo", "ngilyo", "ngixyo", "nngilyo", "nngixyo", "nngyo", "xngilyo", "xngixyo", "xngyo"],
    "んしゃ": ["nnsha", "nnsilya", "nnsixya", "nnsya", "nsha", "nsilya", "nsixya", "nsya", "xnsha", "xnsilya", "xnsixya", "xnsya"], "んしゅ": ["nnshu", "nnsilyu", "nnsixyu", "nnsyu", "nshu", "nsilyu", "nsixyu", "nsyu", "xnshu", "xnsilyu", "xnsixyu", "xnsyu"], "んしょ": ["nnsho", "nnsilyo", "nnsixyo", "nnsyo", "nsho", "nsilyo", "nsixyo", "nsyo", "xnsho", "xnsilyo", "xnsixyo", "xnsyo"],
    "んじゃ": ["nja", "njilya", "njixya", "njya", "nnja", "nnjilya", "nnjixya", "nnjya", "nnzilya", "nnzixya", "nnzya", "nzilya", "nzixya", "nzya", "xnja", "xnjilya", "xnjixya", "xnjya", "xnzilya", "xnzixya", "xnzya"], "んじゅ": ["njilyu", "njixyu", "nju", "njyu", "nnjilyu", "nnjixyu", "nnju", "nnjyu", "nnzilyu", "nnzixyu", "nnzyu", "nzilyu", "nzixyu", "nzyu", "xnjilyu", "xnjixyu", "xnju", "xnjyu", "xnzilyu", "xnzixyu", "xnzyu"], "んじょ": ["njilyo", "njixyo", "njo", "njyo", "nnjilyo", "nnjixyo", "nnjo", "nnjyo", "nnzilyo", "nnzixyo", "nnzyo", "nzilyo", "nzixyo", "nzyo", "xnjilyo", "xnjixyo", "xnjo", "xnjyo", "xnzilyo", "xnzixyo", "xnzyo"],
    "んちゃ": ["ncha", "nncha", "nntilya", "nntixya", "nntya", "ntilya", "ntixya", "ntya", "xncha", "xntilya", "xntixya", "xntya"], "んちゅ": ["nchu", "nnchu", "nntilyu", "nntixyu", "nntyu", "ntilyu", "ntixyu", "ntyu", "xnchu", "xntilyu", "xntixyu", "xntyu"], "んちょ": ["ncho", "nncho", "nntilyo", "nntixyo", "nntyo", "ntilyo", "ntixyo", "ntyo", "xncho", "xntilyo", "xntixyo", "xntyo"],
    "んぢゃ": ["ndilya", "ndixya", "ndya", "nndilya", "nndixya", "nndya", "xndilya", "xndixya", "xndja", "xndya"], "んぢゅ": ["ndilyu", "ndixyu", "ndyu", "nndilyu", "nndixyu", "nndyu", "xndilyu", "xndixyu", "xndyu"], "んぢょ": ["ndilyo", "ndixyo", "ndyo", "nndilyo", "nndixyo", "nndyo", "xndilyo", "xndixyo", "xndyo"],
    "んひゃ": ["nhya", "nhilya", "nhixya", "nnhilya", "nnhixya", "nnhya", "xnhilya", "xnhixya", "xnhya"], "んひゅ": ["nhyu", "nhilyu", "nhixyu", "nnhilyu", "nnhixyu", "nnhyu", "xnhilyu", "xnhixyu", "xnhyu"], "んひょ": ["nhyo", "nhilyo", "nhixyo", "nnhilyo", "nnhixyo", "nnhyo", "xnhilyo", "xnhixyo", "xnhyo"],
    "んびゃ": ["nbya", "nbilya", "nbixya", "nnbilya", "nnbixya", "nnbya", "xnbilya", "xnbixya", "xnbya"], "んびゅ": ["nbyu", "nbilyu", "nbixyu", "nnbilyu", "nnbixyu", "nnbyu", "xnbilyu", "xnbixyu", "xnbyu"], "んびょ": ["nbyo", "nbilyo", "nbixyo", "nnbilyo", "nnbixyo", "nnbyo", "xnbilyo", "xnbixyo", "xnbyo"],
    "んぴゃ": ["npya", "nnpilya", "nnpixya", "nnpya", "npilya", "npixya", "xnpilya", "xnpixya", "xnpya"], "んぴゅ": ["npyu", "nnpilyu", "nnpixyu", "nnpyu", "npilyu", "npixyu", "xnpilyu", "xnpixyu", "xnpyu"], "んぴょ": [ "npyo","nnpilyo", "nnpixyo", "nnpyo", "npilyo", "npixyo", "xnpilyo", "xnpixyo", "xnpyo"],
    "んみゃ": ["nmya","nmilya", "nmixya",  "nnmilya", "nnmixya", "nnmya", "xnmilya", "xnmixya", "xnmya"], "んみゅ": ["nmyu","nmilyu", "nmixyu",  "nnmilyu", "nnmixyu", "nnmyu", "xnmilyu", "xnmixyu", "xnmyu"], "んみょ": ["nmyo","nmilyo", "nmixyo",  "nnmilyo", "nnmixyo", "nnmyo", "xnmilyo", "xnmixyo", "xnmyo"],
    "んりゃ": ["nrya", "nnrilya", "nnrixya", "nnrya", "nrilya", "nrixya", "xnrilya", "xnrixya", "xnrya"], "んりゅ": ["nryu","nnrilyu", "nnrixyu", "nnryu", "nrilyu", "nrixyu",  "xnrilyu", "xnrixyu", "xnryu"], "んりょ": ["nryo", "nnrilyo", "nnrixyo", "nnryo", "nrilyo", "nrixyo", "xnrilyo", "xnrixyo", "xnryo"]
};
export default kanaPatterns;