const kanaPatterns = {
  "あ": ["a"],   "い": ["i"],   "う": ["u"],   "え": ["e"],   "お": ["o"],
  "か": ["ka"],  "き": ["ki"],  "く": ["ku"],  "け": ["ke"],  "こ": ["ko"],
  "さ": ["sa"],  "し": ["shi", "si"],  "す": ["su"],  "せ": ["se"],  "そ": ["so"],
  "た": ["ta"],  "ち": ["chi", "ti"],  "つ": ["tsu", "tu"],  "て": ["te"],  "と": ["to"],
  "な": ["na"],  "に": ["ni"],  "ぬ": ["nu"],  "ね": ["ne"],  "の": ["no"],
  "は": ["ha"],  "ひ": ["hi"],  "ふ": ["fu", "hu"],  "へ": ["he"],  "ほ": ["ho"],
  "ま": ["ma"],  "み": ["mi"],  "む": ["mu"],  "め": ["me"],  "も": ["mo"],
  "や": ["ya"],                 "ゆ": ["yu"],                "よ": ["yo"],
  "ら": ["ra"],  "り": ["ri"],  "る": ["ru"],  "れ": ["re"],  "ろ": ["ro"],
  "わ": ["wa"],  "を": ["wo"],  "ん": ["n"],
  "が": ["ga"],  "ぎ": ["gi"],  "ぐ": ["gu"],  "げ": ["ge"],  "ご": ["go"],
  "ざ": ["za"],  "じ": ["ji", "zi"],  "ず": ["zu"],  "ぜ": ["ze"],  "ぞ": ["zo"],
  "だ": ["da"],  "ぢ": ["di"],  "づ": ["du"],  "で": ["de"],  "ど": ["do"],
  "ば": ["ba"],  "び": ["bi"],  "ぶ": ["bu"],  "べ": ["be"],  "ぼ": ["bo"],

  // 半濁音
  "ぱ": ["pa"],  "ぴ": ["pi"],  "ぷ": ["pu"],  "ぺ": ["pe"],  "ぽ": ["po"],
  "きゃ": ["kya"], "きゅ": ["kyu"], "きょ": ["kyo"],
  "ぎゃ": ["gya"], "ぎゅ": ["gyu"], "ぎょ": ["gyo"],
  "しゃ": ["sha", "sya"], "しゅ": ["shu", "syu"], "しょ": ["sho", "syo"],
  "じゃ": ["ja", "jya", "zya"], "じゅ": ["ju", "jyu", "zyu"], "じょ": ["jo", "jyo", "zyo"],
  "ちゃ": ["cha", "tya"], "ちゅ": ["chu", "tyu"], "ちょ": ["cho", "tyo"],
  "にゃ": ["nya"], "にゅ": ["nyu"], "にょ": ["nyo"],
  "ひゃ": ["hya"], "ひゅ": ["hyu"], "ひょ": ["hyo"],
  "びゃ": ["bya"], "びゅ": ["byu"], "びょ": ["byo"],
  "ぴゃ": ["pya"], "ぴゅ": ["pyu"], "ぴょ": ["pyo"],
  "みゃ": ["mya"], "みゅ": ["myu"], "みょ": ["myo"],
  "りゃ": ["rya"], "りゅ": ["ryu"], "りょ": ["ryo"],
  // 促音（手動追加）
  "っか": ["kka"], "っき": ["kki"], "っく": ["kku"], "っけ": ["kke"], "っこ": ["kko"],
  "っさ": ["ssa"], "っし": ["sshi", "ssi"], "っす": ["ssu"], "っせ": ["sse"], "っそ": ["sso"],
  "った": ["tta"], "っち": ["cchi", "tti"], "っつ": ["ttsu", "ttu"], "って": ["tte"], "っと": ["tto"],
  "っは": ["hha"], "っひ": ["hhi"], "っふ": ["ffu", "hhu"], "っへ": ["hhe"], "っほ": ["hho"],
  "っま": ["mma"], "っみ": ["mmi"], "っむ": ["mmu"], "っめ": ["mme"], "っも": ["mmo"],
  "っら": ["rra"], "っり": ["rri"], "っる": ["rru"], "っれ": ["rre"], "っろ": ["rro"],
  "っきゃ": ["kkya"], "っきゅ": ["kkyu"], "っきょ": ["kkyo"],
  "っしゃ": ["ssha", "ssya"], "っしゅ": ["sshu", "ssyu"], "っしょ": ["ssho", "ssyo"],
  "っちゃ": ["ccha", "ttya"], "っちゅ": ["cchu", "ttyu"], "っちょ": ["ccho", "ttyo"],

  //ん系
  "ん": ["nn", "xn"],
"んか": ["nka","nnka","xnka"],"んき": ["nki","nnki","xnki"],"んく": ["nku","nnku","xnku"],"んけ": ["nke","nnke","xnke"],"んこ": ["nko","nnko","xnko"],
"んさ": ["nnsa","nsa","xnsa"],"んし": ["nnshi","nnsi","nshi","nsi","xnshi","xnsi"],"んす": ["nnsu","nsu","xnsu"],"んせ": ["nnse","nse","xnse"],"んそ": ["nnso","nso","xnso"],
"んた": ["nnta","nta","xnta"],"んち": ["nchi","nnchi","nnti","nti","xnchi","xnti"],"んつ": ["nntsu","nntu","ntsu","ntu","xntsu","xntu"],"んて": ["nnte","nte","xnte"],"んと": ["nnto","nto","xnto"],
"んは": ["nha","nnha","xnha"],"んひ": ["nhi","nnhi","xnhi"],"んふ": ["nfu","nhu","nnfu","nnhu","xnfu","xnhu"],"んへ": ["nhe","nnhe","xnhe"],"んほ": ["nho","nnho","xnho"],
"んま": ["nma","nnma","xnma"],"んみ": ["nmi","nnmi","xnmi"],"んむ": ["nmu","nnmu","xnmu"],"んめ": ["nme","nnme","xnme"],"んも": ["nmo","nnmo","xnmo"],
"んや": ["nnya","nya","xnya"],"んゆ": ["nnyu","nyu","xnyu"],"んよ": ["nnyo","nyo","xnyo"],
"んら": ["nnra","nra","xnra"],"んり": ["nnri","nri","xnri"],"んる": ["nnru","nru","xnru"],"んれ": ["nnre","nre","xnre"],"んろ": ["nnro","nro","xnro"],
"んわ": ["nnwa","nwa","xnwa"],"んを":["nnwo","nwo","xnwo"],
"んが": ["nga","nnga","xnga"],"んぎ": ["ngi","nngi","xngi"],"んぐ": ["ngu","nngu","xngu"],"んげ": ["nge","nnge","xnge"],"んご": ["ngo","nngo","xngo"],
"んざ": ["nnza","nza","xnza"],"んじ": ["nji","nnji","nnzi","nzi","xnji","xnzi"],"んず": ["nnzu","nzu","xnzu"],"んぜ": ["nnze","nze","xnze"],"んぞ": ["nnzo","nzo","xnzo"],
"んだ": ["nda","nnda","xnda"],"んぢ": ["ndi","nndi","xndi"],"んづ": ["ndu","nndu","xndu"],"んで": ["nde","nnde","xnde"],"んど": ["ndo","nndo","xndo"],
"んば": ["nba","nnba","xnba"],"んび": ["nbi","nnbi","xnbi"],"んぶ": ["nbu","nnbu","xnbu"],"んべ": ["nbe","nnbe","xnbe"],"んぼ": ["nbo","nnbo","xnbo"],
"んぱ": ["nnpa","npa","xnpa"],"んぴ": ["nnpi","npi","xnpi"],"んぷ": ["nnpu","npu","xnpu"],"んぺ": ["nnpe","npe","xnpe"],"んぽ": ["nnpo","npo","xnpo"],
"んきゃ": ["nkya","nnkya","xnkya"],"んきゅ": ["nkyu","nnkyu","xnkyu"],"んきょ": ["nkyo","nnkyo","xnkyo"],
"んぎゃ": ["ngya","nngya","xngya"],"んぎゅ": ["ngyu","nngyu","xngyu"],"んぎょ": ["ngyo","nngyo","xngyo"],
"んしゃ": ["nnsha","nnsya","nsha","nsya","xnsha","xnsya"],"んしゅ": ["nnshu","nnsyu","nshu","nsyu","xnshu","xnsyu"],"んしょ": ["nnsho","nnsyo","nsho","nsyo","xnsho","xnsyo"],
"んじゃ": ["nja","njya","nnja","nnjya","nnzya","nzya","xnja","xnjya","xnzya"],"んじゅ": ["nju","njyu","nnju","nnjyu","nnzyu","nzyu","xnju","xnjyu","xnzyu"],"んじょ": ["njo","njyo","nnjo","nnjyo","nnzyo","nzyo","xnjo","xnjyo","xnzyo"],
"んちゃ": ["ncha","nncha","nntya","ntya","xncha","xntya"],"んちゅ": ["nchu","nnchu","nntyu","ntyu","xnchu","xntyu"],"んちょ": ["ncho","nncho","nntyo","ntyo","xncho","xntyo"],
"んぢゃ": ["ndja","ndya","nndja","nndya","xndja","xndya"],"んぢゅ": ["ndyu","nndyu","xndyu"],"んぢょ": ["ndyo","nndyo","xndyo"],
"んひゃ": ["nhya","nnhya","xnhya"],"んひゅ": ["nhyu","nnhyu","xnhyu"],"んひょ": ["nhyo","nnhyo","xnhyo"],
"んびゃ": ["nbya","nnbya","xnbya"],"んびゅ": ["nbyu","nnbyu","xnbyu"],"んびょ": ["nbyo","nnbyo","xnbyo"],
"んぴゃ": ["nnpya","npya","xnpya"],"んぴゅ": ["nnpyu","npyu","xnpyu"],"んぴょ": ["nnpyo","npyo","xnpyo"],
"んみゃ": ["nmya","nnmya","xnmya"],"んみゅ": ["nmyu","nnmyu","xnmyu"],"んみょ": ["nmyo","nnmyo","xnmyo"],
"んりゃ": ["nnrya","nrya","xnrya"],"んりゅ": ["nnryu","nryu","xnryu"],"んりょ": ["nnryo","nryo","xnryo"]



};
export default kanaPatterns;